name: chatmesdk_example
description: Demonstrates how to use the chatmesdk plugin.

publish_to: "none"

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  chatmesdk:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
