name: chatmesdk
description: A new Flutter plugin project.
version: 0.0.1
homepage: chatmesdk

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  sound_stream:
    git:
      url: https://github.com/routmartin/flutter-sound-stream.git
      ref: 9a8b693
  assets_audio_player: ^3.0.6
  audio_session: ^0.1.18
  audio_waveforms: ^1.0.4
  azlistview: ^2.0.0
  catcher: 0.7.0
  collection: 1.17.1
  connectivity_plus: ^2.3.9
  country_dial_code: ^1.2.0
  cr_file_saver: ^0.0.2+1
  cupertino_icons: ^1.0.2
  custom_pop_up_menu: ^1.2.4
  custom_timer: ^0.2.3
  debounce_builder: ^0.9.0
  device_info_plus: ^7.0.0
  draggable_widget: ^2.0.0
  easy_debounce: ^2.0.3
  file_picker: ^5.2.7
  flick_video_player: ^0.5.0
  flutter_app_badger: ^1.5.0
  flutter_cache_manager: ^3.3.0
  flutter_inappwebview: ^5.7.2+3
  flutter_native_image: ^0.0.6+1
  flutter_parsed_text: ^2.2.1
  flutter_pdfview: 1.2.2
  flutter_pretty_dio_logger: ^2.0.3
  flutter_screenutil: ^5.6.1
  flutter_slidable: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_udid: ^2.0.1
  flutter_widget_from_html: ^0.8.5
  get: ^4.6.5
  get_storage: ^2.0.3
  grouped_list: ^5.1.2
  http_parser: ^4.0.2
  image_cropper: ^3.0.1
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.6+2
  intl: ^0.17.0
  link_preview_generator: ^1.1.0
  mno_zoom_widget: ^0.1.0
  modal_bottom_sheet: ^3.0.0-pre
  moment_dart: ^0.17.4
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  plugin_platform_interface: ^2.0.2
  scrollable_positioned_list: ^0.2.3
  scrollview_observer: ^1.14.0
  share_plus: ^6.3.1
  show_up_animation: ^2.0.0
  simple_animations: ^5.0.2
  socket_io_client: ^2.0.1
  sound_mode: ^2.0.2
  url_launcher: 6.1.8
  vibration: ^1.7.7
  video_player: ^2.6.1
  video_thumbnail: ^0.5.3
  web_socket_channel: ^2.4.0
  webview_flutter: ^3.0.4
  wechat_assets_picker: ^8.0.0
  wechat_camera_picker: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
